<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'

interface Session { initialized:boolean; authenticated:boolean; user:string; csrf:string }
interface Instance { instance:{id:string;role:string;managed:boolean}; config:{revision:string;text:string;values:Record<string,any>;editable:boolean;reason?:string}; verification:Record<string,string>;runtime?:{process:{state:string;pid:number};layers:Record<string,{status:string;evidence:string;source:string;checkedAt:number}>;proxies:{name:string;type:string;status:string}[]};error?:string }
interface Plan { id:string;instance:string;before:string;after:string;revision:string;validation:string;impact:string }
interface Operation { id:string;instance:string;state:string;created:number;result:string;hasBackup:boolean }
const session=ref<Session>({initialized:false,authenticated:false,user:'',csrf:''})
const user=ref('admin'),password=ref(''),busy=ref(false),error=ref(''),notice=ref('')
const page=ref('overview'),instances=ref<Instance[]>([]),operations=ref<Operation[]>([]),audit=ref<any[]>([])
const current=computed(()=>instances.value.find(x=>x.instance.role===(page.value==='server'?'frps':'frpc')))
const proxies=computed<any[]>(()=>current.value?.config?.values?.proxies||[])
const editor=ref(false),raw=ref(''),plan=ref<Plan|null>(null),proxyEditor=ref(false),original=ref('')
const proxy=ref({name:'',type:'tcp',localIP:'127.0.0.1',localPort:8080,remotePort:16000,customDomains:'',locations:'/',enabled:true})
const install=ref({role:'frpc',mode:'systemd',server:'127.0.0.1',port:17000}),installResult=ref<any>(null)
const nginx=ref({domain:'console.example.test',prefix:'/',upstream:'127.0.0.1',port:18745,tls:false,cert:'/etc/ssl/console.crt',key:'/etc/ssl/console.key',websocket:true}),nginxResult=ref<any>(null)
const search=ref(''),typeFilter=ref('all')
const filtered=computed(()=>proxies.value.filter(p=>(typeFilter.value==='all'||p.type===typeFilter.value)&&JSON.stringify(p).toLowerCase().includes(search.value.toLowerCase())))
const nav=[['overview','◈','工作概览'],['client','⇄','客户端'],['server','▥','服务端'],['changes','↶','变更与备份'],['installer','↓','安装计划'],['nginx','◇','反代模板'],['audit','≡','操作审计']]
const titles:Record<string,string>={overview:'工作概览',client:'客户端管理',server:'服务端管理',changes:'变更与备份',installer:'安装计划',nginx:'反代模板',audit:'操作审计'}
const layerNames:Record<string,string>={installation:'安装就绪',process:'进程运行',authentication:'认证连接',registration:'代理注册',localService:'本地服务',business:'实际业务'}
const statusNames:Record<string,string>={passed:'已通过',failed:'未通过',not_checked:'未验证'}
async function verify(i:Instance){await run(async()=>{await api('/instances/'+i.instance.id+'/verify',{});await refresh();notice.value='已按登记目标检查。结论带来源与时间；没有登记协议探针的项目仍未验证。'})}
const time=(n:number)=>new Date(n*1000).toLocaleString()
async function api(path:string,body?:unknown):Promise<any>{const response=await fetch('/api'+path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json','X-FRP-Console':'1','X-CSRF-Token':session.value.csrf},body:body===undefined?undefined:JSON.stringify(body)});const data=await response.json();if(!response.ok){if(response.status===401)session.value.authenticated=false;throw new Error(data.error||'操作失败')}return data}
async function run(fn:()=>Promise<void>){if(busy.value)return;busy.value=true;error.value='';notice.value='';try{await fn()}catch(e){error.value=e instanceof Error?e.message:'操作失败'}finally{busy.value=false}}
async function refresh(){instances.value=(await api('/instances')).filter((x:Instance)=>x.config);operations.value=await api('/operations');audit.value=await api('/audit')}
async function login(){await run(async()=>{const data=await api(session.value.initialized?'/login':'/bootstrap',{user:user.value,password:password.value});password.value='';session.value={initialized:true,authenticated:true,...data};await refresh()})}
async function logout(){await run(async()=>{await api('/logout',{});session.value.authenticated=false;plan.value=null;raw.value='';proxyEditor.value=false})}
function openRaw(){if(!current.value)return;raw.value=current.value.config.text;editor.value=true}
async function previewRaw(){await run(async()=>{plan.value=await api('/plans',{instance:current.value!.instance.id,revision:current.value!.config.revision,text:raw.value});editor.value=false})}
function openProxy(p?:any){original.value=p?.name||'';proxy.value={name:p?.name||'',type:p?.type||'tcp',localIP:p?.localIP||'127.0.0.1',localPort:p?.localPort||8080,remotePort:p?.remotePort||16000,customDomains:(p?.customDomains||[]).join(', '),locations:(p?.locations||['/']).join(', '),enabled:p?.enabled!==false};proxyEditor.value=true}
async function proxyPlan(name:string,fields:Record<string,any>,remove=false){plan.value=await api('/proxy-plan',{instance:current.value!.instance.id,revision:current.value!.config.revision,name,fields,remove})}
async function saveProxy(){await run(async()=>{const p=proxy.value;const fields:Record<string,any>={name:p.name,type:p.type,localIP:p.localIP,localPort:Number(p.localPort),enabled:p.enabled};if(['tcp','udp'].includes(p.type))fields.remotePort=Number(p.remotePort);else fields.customDomains=p.customDomains.split(',').map(x=>x.trim()).filter(Boolean);if(p.type==='http')fields.locations=p.locations.split(',').map(x=>x.trim()).filter(Boolean);await proxyPlan(original.value,fields);proxyEditor.value=false})}
async function toggle(p:any){await run(()=>proxyPlan(p.name,{enabled:p.enabled===false}))}
async function removeProxy(p:any){await run(()=>proxyPlan(p.name,{},true))}
async function apply(){await run(async()=>{await api('/plans/'+plan.value!.id+'/apply',{});plan.value=null;await refresh();notice.value='隔离配置已保存并备份。没有启动或重载 FRP；运行与业务状态仍未验证。'})}
async function cancel(){await run(async()=>{await api('/plans/'+plan.value!.id+'/cancel',{});plan.value=null;await refresh();notice.value='预览已取消，配置与服务均未修改。'})}
async function restore(op:Operation){await run(async()=>{const data=await api('/plans/'+op.id+'/restore',{});plan.value=data.result})}
onMounted(()=>run(async()=>{session.value=await api('/session');if(session.value.authenticated)await refresh()}))
</script>

<template>
 <div v-if="!session.authenticated" class="login-shell">
  <div class="login-story"><div class="brand"><span class="brand-icon">⇄</span> FRP <b>CONSOLE</b></div><div><span class="eyebrow">独立运行 · 本机管理</span><h1>让连接清晰，<br>让变更可控。</h1><p>客户端与服务端配置，在一个清楚的工作界面里。<br>每次变更都有预览、备份和可核对的结果。</p></div><small>FOUNDATION BUILD · 隔离开发版本</small></div>
  <form class="login-card" @submit.prevent="login"><span class="eyebrow">FRP CONSOLE</span><h2>{{session.initialized?'欢迎回来':'初始化管理员'}}</h2><p>{{session.initialized?'登录本机控制台，继续管理配置。':'首次访问，请创建本机管理员账户。'}}</p><label>用户名<input v-model="user" autocomplete="username" required maxlength="64"></label><label>密码<input v-model="password" type="password" :autocomplete="session.initialized?'current-password':'new-password'" required placeholder="输入密码"></label><div v-if="error" class="error" role="alert">{{error}}</div><button class="primary" :disabled="busy">{{busy?'处理中…':session.initialized?'登录控制台':'创建管理员并进入'}}</button><small>已安装的 FRP 独立运行。配置保存不会自动重载；已有部署只读。</small></form>
 </div>
 <div v-else class="app-shell">
  <aside class="sidebar"><div class="brand"><span class="brand-icon">⇄</span><div>FRP <b>CONSOLE</b></div></div><div class="section-label">本机工作空间</div><nav><button v-for="item in nav" :key="item[0]" :class="{active:page===item[0]}" @click="page=item[0]"><span>{{item[1]}}</span>{{item[2]}}</button></nav><div class="sidebar-footer"><span class="status-dot"></span><div>隔离开发版本<small>官方 FRP 独立运行</small></div></div></aside>
  <div class="workspace"><header><div>工作空间 <span>/</span> {{titles[page]}}</div><div class="header-actions"><span class="tag">FOUNDATION</span><span class="avatar">{{session.user.slice(0,1).toUpperCase()}}</span><button class="text-button" @click="logout">退出</button></div></header>
   <main><div class="page-heading"><div><span class="eyebrow">FRP CONSOLE / {{page.toUpperCase()}}</span><h1>{{titles[page]}}</h1><p>配置有归属，变更有预览，验证有证据。</p></div><button class="secondary" :disabled="busy" @click="run(refresh)">↻ 刷新</button></div>
    <div class="notice"><span>i</span><div><strong>当前为 systemd 安装与验证阶段</strong><p>提供 CLI 自动安装、登记实例状态和分层验证。网页安装执行、运行控制与 Nginx 加载待接入。</p></div></div>
    <div v-if="error" class="error" role="alert">{{error}}</div><div v-if="notice" class="success" role="status">{{notice}}</div>
    <template v-if="page==='overview'">
     <div class="metrics"><article><small>配置实例</small><strong>{{instances.length}}</strong><span>客户端 / 服务端</span></article><article><small>配置变更</small><strong>{{operations.filter(x=>x.state==='saved_offline').length}}</strong><span>已保存至隔离文件</span></article><article><small>备份记录</small><strong>{{operations.filter(x=>x.hasBackup).length}}</strong><span>加密保存 · 可恢复</span></article><article><small>业务验证</small><strong>{{instances.filter(i=>i.verification.business==='passed').length}}</strong><span>通过的实例 · 仅覆盖登记探针</span></article></div>
     <section class="panel"><div class="panel-heading"><h2>配置实例</h2><span class="tag">本机</span></div><div v-if="!instances.length" class="empty">尚未注册实例。用 --demo 创建隔离配置，或通过启动参数导入只读配置。</div><div v-for="i in instances" :key="i.instance.id" class="instance-row"><div class="role-icon">{{i.instance.role==='frpc'?'⇄':'▥'}}</div><div class="grow"><h3>{{i.instance.role==='frpc'?'客户端':'服务端'}} <span class="code">{{i.instance.id}}</span></h3><p>{{i.instance.managed?'程序创建的隔离配置':'导入配置 · 只读'}}</p></div><span class="badge neutral">{{statusNames[i.verification.process]||'未验证'}}</span><button class="secondary" @click="page=i.instance.role==='frpc'?'client':'server'">查看配置 →</button></div></section>
     <section class="panel"><div class="panel-heading"><h2>验证分层</h2><small>各层分别呈现证据</small></div><div class="verification"><div v-for="label in ['安装就绪','进程正常','认证连接','代理注册','本地服务','实际业务']" :key="label"><span class="empty-dot"></span><strong>{{label}}</strong><small>未验证</small></div></div></section>
    </template>
    <template v-if="page==='client'||page==='server'">
     <div v-if="!current" class="panel empty">当前角色没有已注册的配置。</div>
     <template v-else><section class="panel connection"><div class="role-icon">{{page==='client'?'⇄':'▥'}}</div><div class="grow"><h2>{{page==='client'?'FRPC 连接配置':'FRPS 服务配置'}}</h2><p v-if="page==='client'">{{current.config.values.serverAddr}} : {{current.config.values.serverPort}}</p><p v-else>监听 {{current.config.values.bindAddr||'0.0.0.0'}} : {{current.config.values.bindPort}}</p><small>{{current.instance.managed?'专属管理配置 · 保存后需显式应用运行':'导入部署 · 只读'}}</small></div><span class="badge neutral">{{statusNames[current.verification.process]||'未验证'}}</span><button class="secondary" @click="openRaw">{{current.config.editable?'编辑配置':'查看配置'}}</button></section><div v-if="!current.config.editable" class="notice">{{current.config.reason}}</div><section class="panel"><div class="panel-heading"><div><h2>分层验证</h2><p>状态来自登记的 systemd 单元与 FRP 本机 API。业务探测只访问安装清单登记的目标。</p></div><button class="primary" :disabled="busy" @click="verify(current)">验证登记目标</button></div><div class="parameter-grid"><div v-for="(label,key) in layerNames" :key="key"><small>{{label}}</small><strong>{{statusNames[current.verification[key]]||'未验证'}}</strong><p>{{current.runtime?.layers[key]?.evidence}}</p><small v-if="current.runtime?.layers[key]?.checkedAt">{{time(current.runtime.layers[key].checkedAt)}} · {{current.runtime.layers[key].source}}</small></div></div><div class="table-footer">验证结果最多缓存 2 分钟；文件修订或进程 PID 变化后失效。业务通过仅覆盖登记探针的执行位置与协议。</div></section><section v-if="current.runtime?.proxies.length" class="panel"><div class="panel-heading"><h2>运行代理</h2><small>来自官方 FRP 管理接口</small></div><table><thead><tr><th>名称</th><th>协议</th><th>运行状态</th></tr></thead><tbody><tr v-for="p in current.runtime.proxies" :key="p.type+p.name"><td>{{p.name}}</td><td>{{p.type}}</td><td>{{p.status}}</td></tr></tbody></table></section>
      <section v-if="page==='client'" class="panel"><div class="panel-heading"><div><h2>代理规则 <span class="count">{{proxies.length}}</span></h2><p>启用状态来自配置文件，运行结果单独验证。</p></div><button class="primary" :disabled="!current.config.editable||busy" @click="openProxy()">＋ 添加代理</button></div><div class="toolbar"><div class="tabs"><button v-for="t in ['all','tcp','udp','http','https']" :key="t" :class="{selected:typeFilter===t}" @click="typeFilter=t">{{t==='all'?'全部':t.toUpperCase()}}</button></div><input v-model="search" placeholder="搜索名称、地址或域名" aria-label="搜索代理"></div><div class="table-scroll"><table><thead><tr><th>代理名称</th><th>协议</th><th>本地服务</th><th>公网入口</th><th>配置状态</th><th>操作</th></tr></thead><tbody><tr v-for="p in filtered" :key="p.name"><td><strong>{{p.name}}</strong></td><td><span class="protocol">{{p.type.toUpperCase()}}</span></td><td class="code">{{p.localIP||'127.0.0.1'}}:{{p.localPort}}</td><td class="code">{{p.remotePort||(p.customDomains||[]).join(', ')||'—'}}</td><td><button class="badge" :class="p.enabled===false?'neutral':'positive'" :disabled="!current.config.editable||busy" @click="toggle(p)">{{p.enabled===false?'已停用':'已启用'}}</button></td><td><div class="row-actions"><button :disabled="!current.config.editable||busy" @click="openProxy(p)">编辑</button><button class="danger-text" :disabled="!current.config.editable||busy" @click="removeProxy(p)">删除</button></div></td></tr></tbody></table><div v-if="!filtered.length" class="empty">没有匹配的代理。</div></div><div class="table-footer">状态仅表示配置意图。TCP 连接与 running 均不等于业务验收。</div></section>
      <section v-else class="panel"><div class="panel-heading"><h2>服务端参数</h2><small>客户端代理定义由客户端配置管理</small></div><div class="parameter-grid"><div v-for="k in ['bindAddr','bindPort','vhostHTTPPort','vhostHTTPSPort','allowPorts','maxPortsPerClient']" :key="k"><small>{{k}}</small><strong>{{current.config.values[k]??'未显式设置'}}</strong></div></div><div class="table-footer">已注册代理的运行状态在上方显示；没有登记 FRPS 管理接口时保持未验证。</div></section>
     </template>
    </template>
    <section v-if="page==='changes'" class="panel"><div class="panel-heading"><h2>操作记录与恢复</h2><small>最多显示最近 100 条</small></div><div class="table-scroll"><table><thead><tr><th>时间</th><th>实例</th><th>状态</th><th>结果</th><th>操作</th></tr></thead><tbody><tr v-for="op in operations" :key="op.id"><td>{{time(op.created)}}</td><td class="code">{{op.instance}}</td><td><span class="badge neutral">{{op.state}}</span></td><td>{{op.result||'候选配置已校验'}}</td><td><button v-if="op.hasBackup&&['saved_offline','recovery_required'].includes(op.state)" class="text-button" :disabled="busy" @click="restore(op)">预览恢复</button></td></tr></tbody></table><div v-if="!operations.length" class="empty">还没有配置操作。</div></div><div class="table-footer">备份内容加密保存在本机。恢复也需要预览和确认，不自动重放未完成的操作。</div></section>
    <template v-if="page==='installer'"><div class="steps"><span v-for="(s,i) in ['环境预检','选择角色','配置导入','部署预览','安装验证']" :key="s">{{i+1}} · {{s}}</span></div><section class="panel"><div class="panel-heading"><div><h2>生成部署计划</h2><p>网页提供模板预览。原生自动安装使用主机上的 install wizard，先预检、预览并确认计划，再创建独立服务。</p></div></div><form class="form-grid" @submit.prevent="run(async()=>{installResult=await api('/install/plan',install)})"><label>安装角色<select v-model="install.role"><option value="frpc">客户端 FRPC</option><option value="frps">服务端 FRPS</option></select></label><label>部署方式<select v-model="install.mode"><option value="systemd">原生 systemd</option><option value="compose">Docker Compose</option></select></label><label>FRPS 地址<input v-model="install.server" required></label><label>FRP 连接端口<input v-model.number="install.port" type="number" min="1024" max="65535" required></label><div class="form-footer"><button class="primary" :disabled="busy">生成并预览</button></div></form></section><template v-if="installResult"><section v-for="f in installResult.files" :key="f.path" class="panel"><div class="panel-heading"><h3 class="code">{{f.path}}</h3><span class="badge neutral">未安装</span></div><pre>{{f.content}}</pre></section><div class="notice">网页模板包含凭据占位符，不能直接安装。主机 CLI：sudo frp-console install wizard。网页没有执行下载或服务修改。</div></template></template>
    <template v-if="page==='nginx'"><section class="panel"><div class="panel-heading"><div><h2>Nginx 配置模板</h2><p>生成独立站点模板，保留现有配置。当前未执行 nginx -t 或 reload。</p></div></div><form class="form-grid" @submit.prevent="run(async()=>{nginxResult=await api('/nginx/preview',nginx)})"><label>域名<input v-model="nginx.domain" required></label><label>路径前缀<input v-model="nginx.prefix" required></label><label>上游地址<input v-model="nginx.upstream" required></label><label>上游端口<input v-model.number="nginx.port" type="number" required></label><label class="checkbox"><input v-model="nginx.tls" type="checkbox">使用现有 HTTPS 证书</label><label class="checkbox"><input v-model="nginx.websocket" type="checkbox">支持 WebSocket</label><label v-if="nginx.tls">证书路径<input v-model="nginx.cert" required></label><label v-if="nginx.tls">私钥路径<input v-model="nginx.key" required></label><div class="form-footer"><button class="primary" :disabled="busy">预览模板</button></div></form></section><section v-if="nginxResult" class="panel"><div class="panel-heading"><h3>{{nginxResult.file.path}}</h3><span class="badge neutral">未校验 · 未加载</span></div><pre>{{nginxResult.file.content}}</pre></section></template>
    <section v-if="page==='audit'" class="panel"><div class="panel-heading"><h2>操作审计</h2><small>凭据不会写入审计内容</small></div><div class="table-scroll"><table><thead><tr><th>时间</th><th>操作者</th><th>操作</th><th>实例</th><th>结果</th></tr></thead><tbody><tr v-for="(a,i) in audit" :key="i"><td>{{time(a.at)}}</td><td>{{a.actor}}</td><td>{{a.action}}</td><td>{{a.instance||'—'}}</td><td>{{a.result}}</td></tr></tbody></table></div></section>
    <footer>FRP Console · 本机配置管理 <span>官方 FRP 独立运行</span></footer>
   </main>
  </div>
 </div>
 <div v-if="editor" class="modal-backdrop"><section class="modal wide"><div class="panel-heading"><div><h2>{{current?.config.editable?'配置编辑':'脱敏配置'}}</h2><p>凭据占位符表示保持原值；可替换为新值。预览前不会写入文件。</p></div><button class="text-button" @click="editor=false">关闭</button></div><textarea v-model="raw" class="config-editor" :readonly="!current?.config.editable" spellcheck="false" aria-label="配置内容"></textarea><div v-if="error" class="error">{{error}}</div><div class="modal-footer"><button class="secondary" @click="editor=false">取消编辑</button><button v-if="current?.config.editable" class="primary" :disabled="busy" @click="previewRaw">校验并预览差异</button></div></section></div>
 <div v-if="proxyEditor" class="modal-backdrop"><section class="modal"><div class="panel-heading"><h2>{{original?'编辑代理':'添加代理'}}</h2><button class="text-button" @click="proxyEditor=false">关闭</button></div><form @submit.prevent="saveProxy"><div class="form-grid"><label>名称<input v-model="proxy.name" required></label><label>类型<select v-model="proxy.type"><option v-for="t in ['tcp','udp','http','https']" :key="t">{{t}}</option></select></label><label>本地地址<input v-model="proxy.localIP" required></label><label>本地端口<input v-model.number="proxy.localPort" type="number" min="1" max="65535" required></label><label v-if="['tcp','udp'].includes(proxy.type)">远端端口<input v-model.number="proxy.remotePort" type="number" min="1" max="65535" required></label><label v-else>域名（逗号分隔）<input v-model="proxy.customDomains" required></label><label v-if="proxy.type==='http'">路径（逗号分隔）<input v-model="proxy.locations" required></label><label class="checkbox"><input v-model="proxy.enabled" type="checkbox">配置为启用</label></div><div v-if="error" class="error">{{error}}</div><div class="modal-footer"><button type="button" class="secondary" @click="proxyEditor=false">取消编辑</button><button class="primary" :disabled="busy">校验并预览</button></div></form></section></div>
 <div v-if="plan" class="modal-backdrop"><section class="modal wide"><div class="panel-heading"><div><h2>确认配置变更</h2><p>官方 FRP 二进制校验已通过。仅保存隔离配置，不启动或重载服务。</p></div><span class="badge positive">校验通过</span></div><div class="diff"><div><small>变更前 · 脱敏</small><pre>{{plan.before}}</pre></div><div><small>变更后 · 脱敏</small><pre>{{plan.after}}</pre></div></div><div class="notice">保存前会重新核对文件修订号。旧配置作为加密备份保留；运行与业务验证不因此变为成功。</div><div v-if="error" class="error">{{error}}</div><div class="modal-footer"><button class="secondary" :disabled="busy" @click="cancel">取消预览</button><button class="primary" :disabled="busy" @click="apply">确认保存隔离配置</button></div></section></div>
</template>
